### ISSUE TITLE
"jump between sections" command gives No tags file error and tag not found error

### ISSUE THREAD

**Issue by sudara999** [arp242/jumpy.vim#11]
![image](https://user-images.githubusercontent.com/39725969/95019321-a3a50600-069f-11eb-8ae6-9dcd0ed5f4ef.png)
When I use the default key bindings to jump to the next section, `g]`, I get the error shown above. I can't figure out why, because I am relatively new to vim. Any help would be appreciated and thanks for the neat plugin!

**Comment by arp242** [comment]
There isn't anything defined for the `c` filetype for `g[` and `g]` (see the table in the README), so this key won't get mapped and you get the default behaviour.

I think this makes sense? I don't know; could perhaps show an error instead, but `g]` is already a (rarely used) builtin mapping, so I'd rather not overwrite it unless there's actually something useful to do.

**Comment by arp242** [comment]
I just added section jumps for C, so that should fix it as well (it's a feature I added later and just added the filetypes I frequently use myself).
