### ISSUE TITLE
Move to first character after jump

### ISSUE THREAD

**Issue by toupeira** [arp242/jumpy.vim#4]
Nice little plugin!

I noticed for some filetypes (e.g. Ruby) it will jump to the whitespace in front of the keyword due to the use of `\s` in the regex. Could you tweak this to move to the first character instead?

Something like this seems to work, but you might see a better way:

```patch
diff --git i/autoload/jumpy.vim w/autoload/jumpy.vim
index b0ed695..333d0c6 100644
--- i/autoload/jumpy.vim
+++ w/autoload/jumpy.vim
@@ -28,8 +28,9 @@ fun! jumpy#jump(pattern, mode, dir) abort
 
 	let l:save = winsaveview()
 	for l:i in range(l:count)
-		let l:loc = search(a:pattern, 'W' . (a:dir is# 'prev' ? 'b' : ''))
+		let l:loc = search(a:pattern, 'Wz' . (a:dir is# 'prev' ? 'b' : ''))
 		if l:loc > 0
+			normal ^
 			continue
 		endif
```

(the addition of `z` to `search()` was necessary to unbreak jumping back with `[[`)

**Comment by arp242** [comment]
Thanks! Should be fixed now.

**Comment by toupeira** [comment]
@arp242 cool thanks, works great! :+1:
